name: PHPCS

on:
  pull_request:
    paths:
      - '**/*.php'
  push:
    branches:
      - main
    paths:
      - '**/*.php'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: '8.1'
      - name: Composer install (dev)
        run: composer install --no-progress --no-interaction
      - name: Run PHPCS
        run: ./vendor/bin/phpcs --standard=phpcs.xml.dist -n
name: PHPCS

on:
  pull_request:
    paths:
      - '**.php'
      - 'phpcs.xml.dist'
      - 'composer.*'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Run PHPCS
        run: vendor/bin/phpcs --report=full
